#!/bin/sh

# PROVIDE: torr-server
# REQUIRE: LOGIN
# KEYWORD: shutdown
#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# torr_server_enable: Set to yes to enable the torr-server service.
#			Default: no

. /etc/rc.subr
name=torr_server
rcvar=${name}_enable
pidfile="/var/run/torr-server.pid"

command="/usr/sbin/daemon"
command_args="-f -p ${pidfile} /usr/local/lib/torr-server/TorrServer-freebsd-amd64"
load_rc_config ${name}
run_rc_command "$1"
